services:
  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=order_service_db
      - POSTGRES_USER=order_service_username
      - POSTGRES_PASSWORD=order_service_password
    ports:
      - "5434:5432"
    volumes:
      - order_db:/var/lib/postgresql/data

  order-service-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

volumes:
  order_db: