services:
  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_DB=order_service_db
      - POSTGRES_USER=order_service_username
      - POSTGRES_PASSWORD=order_service_password
    ports:
      - "5434:5432"
    volumes:
      - order_db:/var/lib/postgresql/data

  order-service-app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres:5432/order_service_db
      - DB_USERNAME=order_service_username
      - DB_PASSWORD=order_service_password
      - JWT_SECRET=KEysWF5PUPofYmqWaCLm2ohD8a+aAnSfKMp12bdMVUYcxeOHBUhEjPzn5LNiExB5px+Mg2gqVmzBxNEOyxSTOQ==

volumes:
  order_db: