spring:
  liquibase:
    change-log: classpath:db/changelog-master.yml
  jpa:
    generate-ddl: false
    show-sql: true
security:
  jwt:
    secret: ${JWT_SECRET}
user-service:
  url: ${USER_SERVICE_URL}
resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true